"""
Airway bill PDF processor.

Workflow (automatic):
  1. Background task polls SharePoint every 5 minutes.
  2. For each new PDF in "7. Operation/Airway Bills/" (root or month sub-folders),
     download and extract airway bill data.
  3. Each PDF page = one airway bill label.  We extract:
       • AWB number  – matches NVMYPRPAW followed by 9 digits
       • Order number – the digits before the parenthesised customer name in the
                        "TO (ADDRESSEE)" block, e.g. "1137 (Chong Joanne)" → "1137"
  4. Search Airtable for the order, write the AWB to the "Airway Bill" field.
  5. Track processed file IDs in a local JSON file to avoid reprocessing.

Manual trigger:
  POST /process-airway-bills
"""

import io
import json
import logging
import re
from pathlib import Path

import pdfplumber

from clients.airtable import AirtableClient
from clients.sharepoint import SharePointClient

logger = logging.getLogger(__name__)

# ── Regex patterns ─────────────────────────────────────────────────────────────

# NinjaVan Malaysia tracking numbers generated by our shipper account
AWB_RE = re.compile(r"NVMYPRPAW\d{9}")

# The "TO (ADDRESSEE)" name field always looks like:
#   "1137 (Chong Joanne)"   or   "00447 (Cindy Chor)"
# i.e.  3–5 digits · space · open-paren · anything · close-paren
ORDER_REF_RE = re.compile(r"\b(\d{3,5})\s+\([^)]+\)")

# ── State file ─────────────────────────────────────────────────────────────────

STATE_FILE = Path("processed_airway_bill_pdfs.json")


def _load_processed() -> set:
    if STATE_FILE.exists():
        try:
            return set(json.loads(STATE_FILE.read_text()))
        except Exception:
            return set()
    return set()


def _save_processed(processed: set) -> None:
    STATE_FILE.write_text(json.dumps(list(processed)))


# ── Processor ─────────────────────────────────────────────────────────────────

class AirwayBillProcessor:
    """
    Polls SharePoint for newly-uploaded airway bill PDFs and writes the AWB
    tracking numbers back to Airtable.
    """

    def __init__(self) -> None:
        self.airtable   = AirtableClient()
        self.sharepoint = SharePointClient()

    # ── Polling entry-point ────────────────────────────────────────────────────

    async def poll_and_process(self) -> None:
        """
        Scan SharePoint for new airway bill PDFs and process any not yet seen.
        Safe to call repeatedly — already-processed files are skipped.
        """
        try:
            processed = _load_processed()
            items     = await self.sharepoint.list_airway_bill_pdfs()
            new_items = [it for it in items if it["id"] not in processed]

            if not new_items:
                logger.debug("No new airway bill PDFs found")
                return

            logger.info(f"Found {len(new_items)} new airway bill PDF(s) to process")
            for item in new_items:
                await self._process_item(item, processed)

        except Exception as exc:
            logger.error(f"Airway bill poll failed: {exc}", exc_info=True)

    async def _process_item(self, item: dict, processed: set) -> None:
        filename = item.get("name", "unknown")
        item_id  = item["id"]
        logger.info(f"Processing airway bill PDF: {filename} (from {item['parentPath']})")
        try:
            pdf_bytes = await self.sharepoint.download_item(item_id)
            results   = await self.process_pdf(pdf_bytes, filename)

            n_updated = sum(1 for r in results if r["updated"])
            n_pages   = len(results)
            logger.info(
                f"{filename}: {n_pages} pages processed — "
                f"{n_updated} Airtable record(s) updated"
            )

            # Mark as processed regardless of individual page outcomes so we
            # don't retry the whole file on the next poll.  Partial failures
            # are logged per-page.
            processed.add(item_id)
            _save_processed(processed)

        except Exception as exc:
            logger.error(f"Failed to process {filename}: {exc}", exc_info=True)
            # Do NOT add to processed — let it retry on the next poll.

    # ── PDF extraction ─────────────────────────────────────────────────────────

    async def process_pdf(self, pdf_bytes: bytes, filename: str = "") -> list[dict]:
        """
        Extract (AWB, order_number) from every page of a PDF and update Airtable.

        Returns one result dict per page::

            {
                "page":         int,
                "awb":          str,   # e.g. "NVMYPRPAW000000458"
                "order_number": str,   # e.g. "1137"
                "record_id":    str | None,
                "updated":      bool,
            }
        """
        results: list[dict] = []

        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            for page_num, page in enumerate(pdf.pages, start=1):
                text = page.extract_text() or ""
                logger.info(f"PDF p{page_num} text: {text[:400]!r}")
                awb, order_number = _extract_awb_and_order(text)

                result: dict = {
                    "page":         page_num,
                    "awb":          awb,
                    "order_number": order_number,
                    "record_id":    None,
                    "updated":      False,
                }

                if not awb:
                    logger.warning(
                        f"{filename} page {page_num}: no AWB number found — skipping"
                    )
                    results.append(result)
                    continue

                if not order_number:
                    logger.warning(
                        f"{filename} page {page_num}: AWB={awb} but no order number found"
                        " — cannot match to Airtable"
                    )
                    results.append(result)
                    continue

                record_id, updated = await self._write_to_airtable(
                    awb, order_number, filename, page_num
                )
                result["record_id"] = record_id
                result["updated"]   = updated
                results.append(result)

        return results

    # ── Airtable write ─────────────────────────────────────────────────────────

    async def _write_to_airtable(
        self,
        awb: str,
        order_number: str,
        filename: str,
        page_num: int,
    ) -> tuple[str | None, bool]:
        """
        Search for the order and write the AWB.

        Returns (record_id, was_updated).
        """
        records = await self.airtable.search_orders(order_number=order_number)

        if not records:
            logger.warning(
                f"{filename} page {page_num}: AWB={awb}, order={order_number!r}"
                " — no matching Airtable record found"
            )
            return None, False

        record    = records[0]
        record_id = record["id"]
        fields    = record.get("fields", {})
        existing  = fields.get("Airway Bill", "")

        if existing == awb:
            logger.info(
                f"{filename} page {page_num}: order={order_number!r} already has"
                f" AWB={awb} — skipping"
            )
            return record_id, False

        if existing:
            logger.warning(
                f"{filename} page {page_num}: order={order_number!r} has existing"
                f" AWB={existing!r}, overwriting with {awb!r}"
            )

        await self.airtable.update_record(record_id, {"Airway Bill": awb})
        logger.info(
            f"✅ {filename} page {page_num}: order={order_number!r}"
            f" → AWB={awb} written to Airtable [{record_id}]"
        )
        return record_id, True


# ── Extraction helpers ─────────────────────────────────────────────────────────

def _extract_awb_and_order(text: str) -> tuple[str, str]:
    """
    Parse a single page's extracted text and return (awb, order_number).

    Both values are empty strings if not found.
    """
    awb_match = AWB_RE.search(text)
    awb = awb_match.group() if awb_match else ""

    # The TO (ADDRESSEE) name always starts with the order number, e.g.:
    #   "1137 (Chong Joanne)"  →  group(1) = "1137"
    #   "00447 (Cindy Chor)"   →  group(1) = "00447"
    order_match = ORDER_REF_RE.search(text)
    order_number = order_match.group(1) if order_match else ""

    return awb, order_number
